language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
# command to install dependencies
env:
  - DJANGO_VERSION=1.7

install:
  - pip install Django==$DJANGO_VERSION

# command to run tests
script: nosetests
